# Simple workflow for deploying static content to GitHub Pages
name: CI

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

env:
  GITBOOKDIR: ~/work/${{ github.event.repository.name }}/gitbook

jobs:
  deploy:
    environment:
      name: AZURE_152
    runs-on: ubuntu-latest
    steps:
      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.AZURE_152_SECRET }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H "${{ vars.AZURE_152_HOST }}" >> ~/.ssh/known_hosts
      
      - name: Checkout mian
        uses: actions/checkout@v4
        with:
          ref: main
          token: ${{ github.token }}
      
      - name: Gitbook Build
        run: |
          ssh ${{ vars.AZURE_152_USER }}@${{ vars.AZURE_152_HOST }} "if [ -d $GITBOOKDIR/notes ]; then sudo rm -rf $GITBOOKDIR/notes; fi"
          scp -r ${{ github.workspace }}/notes ${{ vars.AZURE_152_USER }}@${{ vars.AZURE_152_HOST }}:$GITBOOKDIR/
          ssh ${{ vars.AZURE_152_USER }}@${{ vars.AZURE_152_HOST }} 'docker run --rm --name gitbook_v3.2.3 -v "/home/v2ray/work/gitbook-docker/gitbook/notes:/gitbook/docs" -v "/home/v2ray/work/gitbook-docker/gitbook/book:/gitbook/_book" -p 80:4000 -it gitbook:3.2.3 gitbook build'
      
      - name: Checkout gh-page
        uses: actions/checkout@v4
        with:
          ref: gh-page
          token: ${{ github.token }}

      - name: Commit
        run: |
          rm -rf ${{ github.workspace }}/book
          scp -r ${{ vars.AZURE_152_USER }}@${{ vars.AZURE_152_HOST }}:$GITBOOKDIR/book  ${{ github.workspace }}/
          cd ${{ github.workspace }}

          git config --global user.name "IRainCoder"
          git config --global user.email "weiqiang.ir@gmail.com"
          git add .
          git commit -am "更新"
      
      - name: Push changes
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          git push
        

